
STYLES = [
    "incorrect",
    "abstract",
    "quirky",
    "minimalist",
    "surreal",
    "zen",
    "modern",
    "bizarre",
    "nonsense",
    "funny",
    "serious",
    "dark",
    "facecious",
    "whimsical",
    "tongue-in-cheek",
    "poor grammar",
    "wrong",
    "confusing",
    "illogical",
    "rhyming",
    "cheesy",
    "farcical",
    "satirical",
    "ironic",
    "sarcastic",
    "sardonic",
    "inspirational",
    "motivational",
    "contradictory",
]