
SUBJECTS = [
    "cats",
    "dogs",
    "hamburgers",
    "pizza",
    "work",
    "school",
    "travel",
    "music",
    "books",
    "beaches",
    "nature",
    "movies",
    "art",
    "family",
    "friends",
    "chocolate",
    "coffee",
    "fitness",
    "meditation",
    "cheese",
    "wine",
    "tardigrades",
    "mice",
    "memes",
    "robots",
    "climbing",
    "white water rafting",
    "comedy",
    "drugs",
    "toilets",
    "public bathrooms",
    "public transit",
]

STYLES = [
    "incorrect",
    "abstract",
    "quirky",
    "minimalist",
    "surreal",
    "zen",
    "modern",
    "bizzare",
    "nonsense",
    "funny",
    "serious",
    "dark",
    "light",
    "facecious",
    "whimsical",
    "tongue-in-cheek",
    "poor grammar",
    "wrong",
    "confusing",
    "illogical",
    "rhyming",
    "cheesy",
]